// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cadastro_pessoas_fisicas_juridicas_api.Infrastructure.Repositories;

#nullable disable

namespace cadastro_pessoas_fisicas_juridicas_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PessoaFisicaId")
                        .IsUnique();

                    b.HasIndex("PessoaJuridicaId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PessoasFisicas");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaJuridica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EhMatriz")
                        .HasColumnType("boolean");

                    b.Property<string>("RamoAtividade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PessoasJuridicas");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PresencaOnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PessoaFisicaId")
                        .IsUnique();

                    b.HasIndex("PessoaJuridicaId")
                        .IsUnique();

                    b.ToTable("PresencasOnline");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .HasColumnType("text");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EhWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<string>("FalarCom")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PessoaFisicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PessoaJuridicaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PessoaFisicaId");

                    b.HasIndex("PessoaJuridicaId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaFisica", "PessoaFisica")
                        .WithOne("Endereco")
                        .HasForeignKey("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Endereco", "PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithOne("Endereco")
                        .HasForeignKey("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Endereco", "PessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PresencaOnLine", b =>
                {
                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaFisica", "PessoaFisica")
                        .WithOne("PresencaOnline")
                        .HasForeignKey("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PresencaOnLine", "PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithOne("PresencaOnline")
                        .HasForeignKey("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PresencaOnLine", "PessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaFisica", "PessoaFisica")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaJuridica", "PessoaJuridica")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaFisica", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("PresencaOnline");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("cadastro_pessoas_fisicas_juridicas_api.Domain.Entities.PessoaJuridica", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("PresencaOnline");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
